# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

c_stdlib_version:  # [osx and x86_64]
  - '10.15'        # [osx and x86_64]

github_actions_labels:          # [linux]
- cirun-openstack-cpu-xlarge    # [linux]
